M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu20.04.1} date Wed 20 Mar 2024 21:38:17 GMT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-20T21:38:17+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X0.2Y-0.2
X0.2Y-2.7
X3.7Y-0.2
X3.7Y-2.7
M30
